name: Set up card sending service

on:
  workflow_dispatch:
    inputs:
      deployment:
        type: choice
        description: DeployOrTearDown
        options:
          - Apply
          - Destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./deployment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["${{ github.workspace }}/iam_lambda.tf"]'
        env:
          S3_BUCKET_IMAGES_URL: ${{ vars.S3_BUCKET_IMAGES_URL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate

      - name: plan
        run: terraform plan

      - name: apply or destroy
        run: |
          if [ ${{ github.event.inputs.deployment }} == 'Apply' ]; then  
            terraform apply -auto-approve
          elif [ ${{ github.event.inputs.deployment }} == 'Destroy' ]; then  
            terraform destroy -auto-approve
          fi
        shell: bash

      - name: Update container image tag to use in ECS
        run: |
          if [ ${{ github.event.inputs.deployment }} == 'Apply' ]; then
            cat outputs.dat
            source outputs.dat
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/LAMBDA_ARN_EMAIL_SERVICE -d '{"name":"LAMBDA_ARN_EMAIL_SERVICE","value":"'$LAMBDAARN'","visibility":"all"}'
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/EVENTBRIDGELAMDBA_ARN_EMAIL_SERVICE -d '{"name":"EVENTBRIDGELAMDBA_ARN_EMAIL_SERVICE","value":"'$EVENTBRIDGETRIGGERLAMBDAROLEARN'","visibility":"all"}'
          elif [ ${{ github.event.inputs.deployment }} == 'Destroy' ]; then  
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/LAMBDA_ARN_EMAIL_SERVICE -d '{"name":"LAMBDA_ARN_EMAIL_SERVICE","value":"'empty'","visibility":"all"}'
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/EVENTBRIDGELAMDBA_ARN_EMAIL_SERVICE -d '{"name":"EVENTBRIDGELAMDBA_ARN_EMAIL_SERVICE","value":"'empty'","visibility":"all"}'

